export const gatoProducts = [
    {
      id: 1,
      category: "Alimentación",
      name: "Croquetas Premium para Gatos",
      description: "Croquetas premium especialmente formuladas para la salud y el bienestar de tu gato. Elaboradas con ingredientes naturales y sabores irresistibles.",
      price: 25,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 2,
      category: "Alimentación",
      name: "Snacks Naturales para Gatos",
      description: "Deliciosos snacks naturales para consentir a tu gato. Elaborados con ingredientes de alta calidad y sin aditivos artificiales.",
      price: 10,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 3,
      category: "Accesorios",
      name: "Torre de Juegos para Gatos",
      description: "Una torre de juegos multi-nivel que mantendrá a tu gato entretenido durante horas. Incluye plataformas, cuevas y juguetes colgantes.",
      price: 50,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 4,
      category: "Accesorios",
      name: "Collar Elegante para Gatos",
      description: "Un collar elegante y seguro para tu gato, con diseño ajustable y detalles brillantes. Ideal para paseos y ocasiones especiales.",
      price: 15,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 5,
      category: "Higiene",
      name: "Arena Absorbente para Gatos",
      description: "Arena ultra absorbente para mantener la bandeja de tu gato limpia y fresca. Con aroma a lavanda para un ambiente más agradable.",
      price: 20,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 6,
      category: "Higiene",
      name: "Champú Suave para Gatos",
      description: "Un champú suave y sin lágrimas diseñado especialmente para gatos. Limpia profundamente el pelaje sin irritar la piel sensible de tu mascota.",
      price: 12,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 7,
      category: "Juguetes",
      name: "Peluche Interactivo para Gatos",
      description: "Un peluche interactivo que estimula el instinto de caza de tu gato. Con movimiento aleatorio y plumas coloridas para horas de diversión.",
      price: 18,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 8,
      category: "Juguetes",
      name: "Caña de Pescar con Catnip",
      description: "Una caña de pescar divertida y estimulante para tu gato, con juguete colgante y aroma a catnip para aumentar su interés y emoción.",
      price: 14,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 9,
      category: "Descanso",
      name: "Cama Suave y Cálida para Gatos",
      description: "Una cama suave y acogedora que brinda un lugar cómodo para que tu gato descanse y se relaje. Con relleno esponjoso y diseño lavable.",
      price: 30,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 10,
      category: "Descanso",
      name: "Cueva Cerrada para Gatos",
      description: "Una cueva cerrada que proporciona un refugio seguro y tranquilo para tu gato. Con diseño acolchado y entrada suave.",
      price: 35,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 11,
      category: "Salud",
      name: "Suplemento Nutricional para Gatos",
      description: "Un suplemento nutricional completo que promueve la salud y el bienestar de tu gato. Formulado con vitaminas esenciales y minerales.",
      price: 28,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 12,
      category: "Salud",
      name: "Cepillo de Masaje para Gatos",
      description: "Un cepillo de masaje suave que estimula la circulación sanguínea y reduce la caída del pelo en tu gato. Perfecto para sesiones de grooming relajantes.",
      price: 16,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 13,
      category: "Moda",
      name: "Chaqueta Deportiva para Gatos",
      description: "Una chaqueta deportiva y elegante para proteger a tu gato del frío y el viento durante sus aventuras al aire libre. Con diseño ligero y ajustable.",
      price: 22,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 14,
      category: "Moda",
      name: "Gorra de Moda para Gatos",
      description: "Una gorra de moda para gatos con estilo único y detalles atractivos. Ideal para proteger a tu gato del sol y agregar un toque de personalidad a su look.",
      price: 10,
      image: "https://via.placeholder.com/150",
    },
    {
      id: 15,
      category: "Transporte",
      name: "Mochila Ventilada para Gatos",
      description: "Una mochila ventilada y segura para llevar a tu gato en tus aventuras al aire libre. Con ventana transparente y correas ajustables para mayor comodidad.",
      price: 40,
      image: "https://via.placeholder.com/150",
    },
  ];
  